# Generated by Django 4.1.2 on 2022-10-31 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('from_kitch_of', models.CharField(blank=True, max_length=50, null=True)),
                ('prep_time', models.CharField(blank=True, max_length=50, null=True)),
                ('cook_time', models.CharField(max_length=50)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('DRINK', 'Drink')], default='LUNCH', max_length=50)),
                ('description', models.TextField()),
                ('posted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('ingredients_used', models.TextField()),
                ('directions', models.TextField()),
                ('posted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipie')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('recipie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipie')),
            ],
        ),
    ]
