# Generated by Django 4.1.4 on 2022-12-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('oven_preheat', models.CharField(default='', max_length=150)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Drink', 'Drink'), ('Alcohol', 'Alcohol')], default='Dinner', max_length=50)),
                ('time_cook', models.IntegerField(default=0)),
                ('serves', models.IntegerField(default=2)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('amount', models.CharField(default='', max_length=150)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
    ]
